sudo: false
dist: trusty
language: cpp

compiler:
    - gcc
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - lcov
      - clang-5.0
      - libboost-dev

before_script:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  - cmake -D Template_ENABLE_COVERAGE:BOOL=TRUE 
          -D Template_USE_OPENMP:BOOL=TRUE 
          -D Template_USE_CLANG_TIDY:BOOL=TRUE 
          . 
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info 
  # filter out system and catch headers
  - lcov --remove coverage.info '/usr/*' 'tests/catch.h' --output-file coverage.info 
  # debug info
  - lcov --list coverage.info 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
