sudo: false
dist: trusty
language: cpp

addons:
  apt:
    packages:

matrix:
  include:
    # XCode 9.2
    - env: CXX=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9.2
      compiler: clang
    # Clang 5.0
    - env: CXX=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - g++-5
            - libboost-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    # GCC 5
    - env: CXX=g++-5 BUILD_TYPE=Debug
      addons: &gcc5
        apt:
          packages: 
            - g++-5
            - lcov
            - libboost-dev
          sources:
            - ubuntu-toolchain-r-test


script:
  - cmake -D Template_ENABLE_COVERAGE:BOOL=TRUE 
          -D Template_USE_OPENMP:BOOL=TRUE 
          -D Template_USE_CLANG_TIDY:BOOL=TRUE 
          -D CMAKE_BUILD_TYPE=$BUILD_TYPE
          . 
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info 
  # filter out system and catch headers
  - lcov --remove coverage.info '/usr/*' 'tests/catch.h' --output-file coverage.info 
  # debug info
  - lcov --list coverage.info 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
